## **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [56]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [50]:
# Ищем делители длины массива a
n = len(a)
d = [x for x in range(1, n + 1) if n % x == 0]
d

[1, 2, 3, 4, 6, 12]

In [51]:
# Выводим все возможные массивы из a
for i in d: 
    print(a.reshape(i, n // i))

[[12 13 14 15 16 17 18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [52]:
#Создаем все возможные массивы с указанным количеством строк
for i in d:
    print(a.reshape(i, -1))

[[12 13 14 15 16 17 18 19 20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [53]:
#Создаем все возможные массивы с указанным количеством столбцов
for i in d:
    print(a.reshape(-1, i))

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [115]:
# зададим одномерный массив a
a = np.arange(1, 13)
print(a)
print("Размерность a: {}".format(a.ndim))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Размерность a: 1


In [117]:
# создадим массив b из 12 строк и 1 столбца
b = np.random.randint(0, 100, (12, 1))
print(b)
print("Размерность b: {}".format(b.ndim))

[[32]
 [32]
 [85]
 [29]
 [85]
 [ 5]
 [63]
 [ 9]
 [57]
 [37]
 [72]
 [62]]
Размерность b: 2


In [118]:
# выбираем элемент из массива a, для этого достаточно одной "координаты" (его элементы проиндексировпны вдоль одной оси axis 0)
a[1]

2

In [119]:
# выбираем элемент массива b, используя одну "координату" (элементы данного массива проиндексированы вдоль ось axis 1)
b[1]

array([32])

In [120]:
#Если требуется получить элемент в виде числа, то необходимо использовать две координаты:
b[1,0]

32

Ответ: массив, состоящий из 12 строк и одного столбца, имеет размерность 2. Однако, его можно считать одномерным массивом, каждый элемент которого является массивом.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [160]:
a = np.random.randn(3, 4)
print(a)
a.size

[[ 0.11066619 -0.13387883 -1.34205828  0.38982794]
 [ 0.00522846 -0.01178558  0.02319903  1.52427305]
 [ 0.15149186  0.16635196  0.22687782 -1.53551692]]


12

In [161]:
b = a.flatten()
print(b)
b.size

[ 0.11066619 -0.13387883 -1.34205828  0.38982794  0.00522846 -0.01178558
  0.02319903  1.52427305  0.15149186  0.16635196  0.22687782 -1.53551692]


12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [208]:
a = np.arange(-20, 0, 2) * (-1)
print(a)
print("Размерность a: {}".format(a.ndim))

[20 18 16 14 12 10  8  6  4  2]
Размерность a: 1


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [209]:
b = a.reshape(1, 10)
print(b)
print("Размерность b: {}".format(b.ndim))

[[20 18 16 14 12 10  8  6  4  2]]
Размерность b: 2


Ответ: Разница между массивами a и b в размерности: dim(a) = 1, dim(b) = 2.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [164]:
a1 = np.zeros((3, 2))
print(a1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [165]:
b1 = np.ones((2, 2))
print(b1)

[[1. 1.]
 [1. 1.]]


In [166]:
v1 = np.concatenate((a1, b1), axis=0)
print(v1)
print("Размер v1: {}".format(v1.size))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
Размер v1: 10


In [167]:
a2 = np.zeros((2, 2))
print(a2)

[[0. 0.]
 [0. 0.]]


In [168]:
b2 = np.ones((3, 2))
print(b2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [169]:
v2 = np.concatenate((a2, b2), axis=0)
print(v2)
print("Размер v2: {}".format(v2.size))

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Размер v2: 10


9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [235]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [236]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [237]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [238]:
B = A.dot(At)
print(B)
print("Размерность матрицы B: {}".format(B.shape))

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размерность матрицы B: (4, 4)


In [239]:
detB = np.linalg.det(B)
if detB == 0:
    print("Обратная матрица для B не существует, т.к. Det(B) = {}".format(detB))
else: 
    print("Обратная матрица для B: {}".format(np.linalg.inv(B))) 

Обратная матрица для B не существует, т.к. Det(B) = 0.0


10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [220]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [230]:
c = np.arange(0, 16)
np.random.shuffle(c)
print(c)

[ 6  2  8 13  9 12 10  3  0 15 14  5 11  7  1  4]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [233]:
C = c.reshape(4,4)
print(C)

[[ 6  2  8 13]
 [ 9 12 10  3]
 [ 0 15 14  5]
 [11  7  1  4]]


In [248]:
D = C*10 + B
print(D)

[[ 65  34 103 162]
 [104 170 186 152]
 [ 23 236 289 262]
 [142 192 222 342]]


In [249]:
# Определитель матрицы D
detD = np.linalg.det(D)
print(detD)

230792999.99999964


In [250]:
# Ранг матрицы D
rankD = np.linalg.matrix_rank(D)
print(rankD)

4


In [265]:
# Обратная матрица для D
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.00341475  0.00975186 -0.00709909 -0.00051319]
 [-0.01830775 -0.00067316  0.00016214  0.00884706]
 [ 0.01614997  0.00753723  0.00316656 -0.01342571]
 [-0.0016231  -0.00856369  0.00080106  0.00688522]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [266]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
print(D_inv)

[[1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 0.]
 [0. 0. 1. 1.]]


In [268]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14   8  13]
 [  9  12  86 122]
 [ 23  86 149   5]
 [ 11   7 212 302]]
